[package]
name = "TermEdit"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = { version = "1", features = ["full"] }  # Async I/O
vte = "0.15.0"  # For escape sequence parsing
arboard = "3.2"
